@startuml
title System sequence diagram
actor Player
participant Startphase
participant "LD, SW, SI, SR, SD, P" as commands
database Local
participant Playphase
participant Q
participant Game_Moves
participant QQ

-> Player: Start of program
Player --> Startphase: Input STARTUP phase
Player <- Startphase: Need Input
Player --> commands: LD, SD
commands --> Local: (LD) Find file
commands -> Local: (SD) Save the deck \n into a file
Startphase <- commands: (LD) If file name not given, \n create new deck
Startphase <- Local: (LD) Load game
Player <- Startphase: Need Input
Player --> commands: SW, SI, SR
Startphase <- commands: Modify deck\n (eg. shuffles cards)
Player <- Startphase: Need Input
Player --> commands: P
commands -> Playphase: Go from startphase to playphase
Player <- Playphase: Need Input
Player --> Q: Q
Startphase <- Q: Go back to startphase
Player <- Playphase: Need Input
Player --> Game_Moves: <from> -> <to>
Playphase <- Game_Moves: Move card
Player --> QQ: Input QQ
QQ ->: End of program
@enduml